configuration: Release
image: Visual Studio 2017
environment:
  repo_url: https://github.com/nikeee/HolzShots
  op_build_user: "Docs Publisher"
  op_build_user_email: "nikeee@users.noreply.github.com"
  # build_docs: false
  access_token:
    secure: FinXsIDAgF1MXSP2tN/e8V2LSSEC4XgSnKI7+Dn2ZV5ae0sh0pke8d9s18RS9a5M
  CI: true

install:
  - ps: cinst scriptcs -y --no-progress
  - scriptcs -version
  - scriptcs -install

before_build:
  - nuget restore HolzShots.sln
  - ps: |
        if($env:build_docs -and (-Not $env:APPVEYOR_PULL_REQUEST_TITLE))
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            cinst docfx -y
            docfx -version
        }
  - scriptcs src\patch-version.csx

test:
  assemblies:
    - src/*.Tests/**/*.Tests.dll

build:
  project: HolzShots.sln

after_build:
  - ps: |
        7z a HolzShots.zip "$env:APPVEYOR_BUILD_FOLDER\src\HolzShots\bin\$env:configuration\*.exe"
        7z a HolzShots.zip "$env:APPVEYOR_BUILD_FOLDER\src\HolzShots\bin\$env:configuration\*.dll"
        7z a HolzShots.zip "$env:APPVEYOR_BUILD_FOLDER\src\HolzShots\bin\$env:configuration\*.config"
        7z a HolzShots.zip "$env:APPVEYOR_BUILD_FOLDER\src\HolzShots\bin\$env:configuration\*.manifest"
  - sha256sum HolzShots.zip > sha256sums.txt
  - ps: |
      $psi = New-Object System.Diagnostics.ProcessStartInfo
      $psi.FileName = "git"
      $psi.RedirectStandardError = $true
      $psi.RedirectStandardOutput = $true
      $psi.UseShellExecute = $false
      $psi.WorkingDirectory = $pwd
      $psi.Arguments = "describe --exact-match --tags HEAD"

      $gitProcess = New-Object System.Diagnostics.Process
      $gitProcess.StartInfo = $psi
      $gitProcess.Start() | Out-Null

      $stdout = $gitProcess.StandardOutput.ReadToEnd()
      $stderr = $gitProcess.StandardError.ReadToEnd()
      $gitProcess.WaitForExit()

      if ($gitProcess.ExitCode -eq 0) {
          Write-Host "Detected tagged commit, building package..."

          $version = $stdout.Substring(1)
          $year = (Get-Date).year.ToString()
          $checksumFile = Get-Content .\sha256sums.txt#
          $checksum = $checksumFile.Split(" ")[0]

          (Get-Content .\package\holzshots.nuspec) -replace '__REPLACE_YEAR__', $year | Set-Content .\package\holzshots.nuspec
          (Get-Content .\package\holzshots.nuspec) -replace '__REPLACE_VERSION__', $version | Set-Content .\package\holzshots.nuspec
          (Get-Content .\package\tools\chocolateyinstall.ps1) -replace '__REPLACE_VERSION__', $version | Set-Content .\package\tools\chocolateyinstall.ps1
          (Get-Content .\package\tools\chocolateyinstall.ps1) -replace '__REPLACE_CHECKSUM__', $checksum | Set-Content .\package\tools\chocolateyinstall.ps1

          choco pack --out . .\package\holzshots.nuspec
      }

artifacts:
  - path: HolzShots.zip
    name: HolzShots
    type: zip
  - path: sha256sums.txt
    name: sha256sums
  - path: holzshots*.nupkg
    name: chocolatey-package

on_success:
  - ps: |
        if($env:build_docs -and (-Not $env:APPVEYOR_PULL_REQUEST_TITLE))
        {
            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
            git config --global user.email $env:op_build_user_email
            git config --global user.name $env:op_build_user
            git config --global core.autocrlf true

            docfx docs/docfx.json

            git clone $env:repo_url -b gh-pages origin_site -q
            Copy-Item origin_site/.git _site -recurse
            CD _site
            git add -A 2>&1
            git commit -m "CI Updates" -q
            git push origin gh-pages -q
        }
